/**
 * Fixtures for this workspace's tests.
 *
 * Not exported from `index.ts` — nothing outside the test suite should import these. Every address
 * here is a deliberately unmistakable fake, on both architectures, and there is **no fixture for any
 * human-only action** on purpose: `set-approval-for-all`, `approve-delegate` and `set-authority` are
 * built inline, once each, in the tests that prove they are refused (AGENTS.md invariant 3 — never
 * in a fixture that could be copy-pasted into production).
 */

import type { PolicyLimits } from "./policy.ts";
import type { AcceptOfferRequest, BuyRequest, CancelOwnListingRequest, TransferRequest } from "./types.ts";
import {
  type Address,
  amountSubject,
  type ChainAddress,
  chainAddress,
  evmAddress,
  type Money,
  money,
  solanaAddress,
  tokenIdSubject,
} from "./types.ts";

// --- EVM ---------------------------------------------------------------------------------------

/** Obviously-fake, well-formed EVM addresses. */
const fakeEvm = (label: string): Address => evmAddress(`0x${label.padEnd(40, "0")}`);

export const ACCOUNT = fakeEvm("acc0");
export const COLLECTION = fakeEvm("c011ec");
export const OTHER_COLLECTION = fakeEvm("badc011ec");
export const MARKETPLACE = fakeEvm("fee");
export const COLD_VAULT = fakeEvm("de5b");
export const ATTACKER = fakeEvm("bad");

export const CHAIN = "ethereum";

/** The same addresses on a *second* EVM chain, for the cross-chain confusion tests. */
export const OTHER_CHAIN = "base";

// --- Solana ------------------------------------------------------------------------------------

/**
 * Obviously-fake, well-formed Solana addresses: an ASCII label padded to 32 bytes with `0xab`.
 *
 * Written as base58 literals rather than derived at import time so the test suite is asserting
 * against fixed strings — a fixture generated by the same encoder the code under test uses would
 * agree with a broken encoder. `solanaAddress` still decodes each one, so a typo is an import-time
 * throw rather than a test that quietly compares two wrong values.
 */
export const SOL_ACCOUNT = solanaAddress("7ZLB8aQLp4Jyvq1EwuJMBxiMpPkxZMvN9KqL3uwpT1gN");
export const SOL_MINT = solanaAddress("7ZLB8aQLp4PpY25QLqUc49fLA2TqyauvYQqdmST5ciMg");
export const SOL_OTHER_MINT = solanaAddress("7ZLB8aQLp4QeDGDiCYsxV9T5q5JmVdVt4VC3SM9idxre");
export const SOL_COLD_VAULT = solanaAddress("7ZLB8aQLp4TRrHsz5EyKecMh86EdD5EfhaXgGgJxJbkn");
export const SOL_ATTACKER = solanaAddress("7ZLB8aQLp4K1V4ns5b3yRm1YqdMVEMh73AotTsfsnQPC");

export const SOL_CHAIN = "solana";

// --- Shared ------------------------------------------------------------------------------------

export const DENOM = "USD-cents";
export const usd = (cents: bigint): Money => money(cents, DENOM);

/** Shorthand for an allowlist entry, since every one is a (chain, address) pair now. */
export const on = (chain: string, addr: Address): ChainAddress => chainAddress(chain, addr);

/** A controllable clock, so rolling-window tests are deterministic rather than slow. */
export function clock(start = 1_700_000_000_000): { now: () => number; advance: (ms: number) => void } {
  let t = start;
  return {
    now: () => t,
    advance: (ms: number) => {
      t += ms;
    },
  };
}

/** Tier-1-ish limits: $25 per transaction, $50 a day, $200 a week. Ethereum only. */
export function limits(overrides: Partial<PolicyLimits> = {}): PolicyLimits {
  return {
    denomination: DENOM,
    perTransaction: 2_500n,
    rolling24h: 5_000n,
    rolling7d: 20_000n,
    allowedActions: ["buy", "accept-offer", "cancel-own-listing", "transfer"],
    contractAllowlist: [on(CHAIN, COLLECTION)],
    withdrawalAllowlist: [on(CHAIN, COLD_VAULT)],
    minAcceptOfferProceeds: 0n,
    approvalTtlMs: 60_000,
    ...overrides,
  };
}

/** The same limits, allowlisting the Solana mint and vault instead. */
export function solanaLimits(overrides: Partial<PolicyLimits> = {}): PolicyLimits {
  return limits({
    contractAllowlist: [on(SOL_CHAIN, SOL_MINT)],
    withdrawalAllowlist: [on(SOL_CHAIN, SOL_COLD_VAULT)],
    ...overrides,
  });
}

const envelope = (id: string, at: number, chain = CHAIN, account: Address = ACCOUNT) => ({
  id,
  requestedAt: at,
  chain,
  account,
});

export function buy(id: string, cents: bigint, at = 0, over: Partial<BuyRequest> = {}): BuyRequest {
  return {
    ...envelope(id, at),
    kind: "buy",
    contract: COLLECTION,
    tokenId: "1",
    maxPrice: usd(cents),
    marketplace: MARKETPLACE,
    ...over,
  };
}

export function acceptOffer(
  id: string,
  cents: bigint,
  at = 0,
  over: Partial<AcceptOfferRequest> = {},
): AcceptOfferRequest {
  return {
    ...envelope(id, at),
    kind: "accept-offer",
    contract: COLLECTION,
    tokenId: "1",
    offerId: "offer-1",
    minProceeds: usd(cents),
    marketplace: MARKETPLACE,
    ...over,
  };
}

export function cancelOwnListing(
  id: string,
  at = 0,
  over: Partial<CancelOwnListingRequest> = {},
): CancelOwnListingRequest {
  return {
    ...envelope(id, at),
    kind: "cancel-own-listing",
    contract: COLLECTION,
    tokenId: "1",
    listingId: "listing-1",
    marketplace: MARKETPLACE,
    ...over,
  };
}

export function transfer(
  id: string,
  cents: bigint,
  to: Address = COLD_VAULT,
  at = 0,
  over: Partial<TransferRequest> = {},
): TransferRequest {
  return {
    ...envelope(id, at),
    kind: "transfer",
    contract: COLLECTION,
    subject: tokenIdSubject("1"),
    to,
    valuation: usd(cents),
    ...over,
  };
}

/** An SPL transfer: a fungible amount out of a mint, to a Solana destination. */
export function solanaTransfer(
  id: string,
  cents: bigint,
  to: Address = SOL_COLD_VAULT,
  at = 0,
  over: Partial<TransferRequest> = {},
): TransferRequest {
  return {
    ...envelope(id, at, SOL_CHAIN, SOL_ACCOUNT),
    kind: "transfer",
    contract: SOL_MINT,
    subject: amountSubject(1_000_000n, 6),
    to,
    valuation: usd(cents),
    ...over,
  };
}
