#!/usr/bin/env bash
# Regenerate each theme's wallpaper from its own colours.
#
# A theme with no `backgrounds/` still applies — `omarchy-theme-set` treats the directory as
# optional — but it leaves whatever wallpaper was there before, so the desktop half of the theme
# ends up being somebody else's. These are computed from the palette rather than fetched or
# generated as art: a fall from `lighter_background` to `background`, one soft wash of `accent`
# blended over it at a low percentage, and a whisper of grain so a 4K gradient does not band on an
# 8-bit panel.
#
# Deliberately not `scripts/generate-asset.ts`. AGENTS.md points that at illustration and ambient
# art; a wallpaper whose whole job is to *be* the theme's own two colours has an exact answer, and a
# generated one could only approximate it — and would have to be regenerated by hand, rather than
# recomputed, the next time a hex value moved.
#
# `-compose blend -define compose:args=N` is a straight N% opacity blend. The obvious-looking
# `-compose Screen` with the same argument is not: it ignores the percentage and paints the wash at
# full strength, which is how the first attempt produced a bright teal spotlight instead of a
# suggestion of one. Look at the output, do not reason about it.
set -euo pipefail

cd "$(dirname "$0")"

value() { grep -oP "^$2 = \"\K[^\"]+" "$1/colors.toml"; }

for theme in harbor lantern driftwood; do
  background=$(value "$theme" background)
  raised=$(value "$theme" lighter_background)
  deep=$(value "$theme" darker_background)
  accent=$(value "$theme" accent)

  # A light theme's ground is at the top of its range, so it falls to `darker_background`; a dark
  # theme's has nowhere below it and rises to `lighter_background` instead.
  if grep -q '^mode = "light"' "$theme/colors.toml"; then
    ramp="$background-$deep"
  else
    ramp="$raised-$background"
  fi

  mkdir -p "$theme/backgrounds"
  magick -size 3840x2160 gradient:"$ramp" \
    \( -size 3840x2160 radial-gradient:"$accent-$background" \) \
    -compose blend -define compose:args=14 -composite \
    -attenuate 0.45 +noise Gaussian -blur 0x1.5 \
    -quality 80 -strip -interlace Plane "$theme/backgrounds/1-$theme.jpg"

  printf '%s: %s\n' "$theme" "$(du -h "$theme/backgrounds/1-$theme.jpg" | cut -f1)"
done
