#!/usr/bin/env node
/**
 * Push the Anchor theme into standalone HTML pages.
 *
 *   node scripts/apply-theme.ts <file.html> [more.html ...]
 *
 * Those pages are deliberately self-contained — no external stylesheet, so they work over file://
 * and survive being copied anywhere. That normally means the palette gets duplicated and drifts.
 *
 * This keeps one source of truth (theme/tokens.css) and syncs it into each page between markers,
 * so re-running after a token change updates every consumer. It appends rather than rewrites: the
 * generated block sits last in the <style>, so it overrides whatever the page defined, and the rest
 * of that page's CSS keeps working untouched.
 *
 * The alias layer maps the older variable names those pages use onto the shared tokens, so nothing
 * has to be renamed to adopt the theme.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const START = "/* anchor-theme:start — generated by scripts/apply-theme.ts; edit theme/tokens.css instead */";
const END = "/* anchor-theme:end */";

const tokens = readFileSync(join(ROOT, "theme", "tokens.css"), "utf8");

/** Take a `:root`-style block out of tokens.css by its opening line. */
function block(header: string): string {
  const at = tokens.indexOf(header);
  if (at === -1) throw new Error(`block not found: ${header}`);
  const open = tokens.indexOf("{", at);
  let depth = 0;
  for (let i = open; i < tokens.length; i++) {
    if (tokens[i] === "{") depth++;
    else if (tokens[i] === "}") {
      depth--;
      if (depth === 0) return tokens.slice(at, i + 1);
    }
  }
  throw new Error(`unbalanced braces after: ${header}`);
}

/* Older pages predate the shared names. Alias rather than rename, so adopting the theme is a
   one-line change per page instead of a rewrite. */
const ALIASES = `
  /* compatibility: names used by the older reference pages */
  --panel: var(--bg-elevated);
  --ink: var(--text);
  --muted: var(--text-muted);
  --line: var(--border);
  --key-bg: var(--code-bg);
  --key-line: var(--border-strong);
  --glow: rgb(var(--accent-rgb) / .10);`;

function themeBlock(): string {
  const palette = block(":root {\n  /* ── depths");
  const light = block(":root {\n  --bg:");
  const dark = block("@media (prefers-color-scheme: dark) {\n  :root {\n    --bg:");
  const lightWithAliases = light.replace(/\n\}$/, `\n${ALIASES}\n}`);
  return [START, palette, lightWithAliases, dark, END].join("\n\n");
}

const files = process.argv.slice(2);
if (files.length === 0) {
  console.error("usage: apply-theme.ts <file.html> [...]");
  process.exit(1);
}

const generated = themeBlock();
for (const file of files) {
  let html = readFileSync(file, "utf8");
  const from = html.indexOf(START);

  if (from !== -1) {
    const to = html.indexOf(END, from);
    if (to === -1) throw new Error(`${file}: start marker without an end marker`);
    html = html.slice(0, from) + generated + html.slice(to + END.length);
  } else {
    // First adoption: append inside the page's own <style> so it wins on cascade order.
    const close = html.lastIndexOf("</style>");
    if (close === -1) throw new Error(`${file}: no <style> block to extend`);
    html = `${html.slice(0, close)}\n${generated}\n${html.slice(close)}`;
  }

  writeFileSync(file, html);
  console.log(`themed ${basename(file)}`);
}
